### ISSUE TITLE
Property 'pushDelegate' not found on object of type 'EMMAPlugin *'

### ISSUE THREAD

**Issue by agomezmart** [EMMADevelopment/Cordova-Plugin-EMMA-SDK#1]
When adding the plugin without any variable `ionic cordova plugin add cordova-plugin-emma-sdk@1.4.7` it shows the following error:

`Property 'pushDelegate' not found on object of type 'EMMAPlugin *'`

And it is because there is no 'pushDelegate' property in the EMMAPlugin and it throws and error.

On the other hand, if the plugin is installed using `ionic cordova plugin add cordova-plugin-emma-sdk@1.4.7 --variable ADD_PUSH=1`, it doesn't throw any error while building but it makes no compatible with other plugins concerning Push notification in iOS, like cordova-plugin-firebasex.

**Comment by rgarciadelongoria** [comment]
I create a PR for this.

https://github.com/EMMADevelopment/Cordova-Plugin-EMMA-SDK/pull/2
